<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE PlayerConfig [
    <!ELEMENT PlayerConfig (playerLife, summonPointsPlayer, deck) >
    <!ELEMENT summonPointsPlayer (#PCDATA)>
    <!ELEMENT playerLife (#PCDATA)>
    <!ELEMENT deck (card)+>
    <!ELEMENT card (name, description, attack, defense)>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT description (#PCDATA)>
    <!ELEMENT attack (#PCDATA)>
    <!ELEMENT defense (#PCDATA)>
    <!ATTLIST card summonPoints (0 | 1 | 2 | 3 | 4 | 5) #REQUIRED>
    <!ATTLIST card type (infantry | chivalry | lancer ) #REQUIRED>
]>
 
<PlayerConfig>
    <playerLife>
    
    </playerLife>
    <summonPointsPlayer>
    
    </summonPointsPlayer>
    <deck>
        <card summonPoints = '1' type = 'chivalry'>
            <name>Estudiante de guerra</name>
            <description>antiguo estudiante de Gideon, poseido por su sed de sangre</description>
            <attack>1</attack>
            <defense>0</defense>
        </card>
        <card summonPoints = '5' type = 'chivalry'>
            <name>Gideon, el jurado</name>
            <description>jefe de los caballeros, traicionado por su rey</description>
            <attack>2</attack>
            <defense>3</defense>
        </card>
        <card summonPoints = '2' type = 'chivalry'>
            <name>Paladines acordantes</name>
            <description>luchan por el sol, y todo lo que este en medio</description>
            <attack>1</attack>
            <defense>1</defense>
        </card>
        <card summonPoints = '4' type = 'chivalry'>
            <name>Paladin plateado</name>
            <description>sub-capitan de la guardia real de Gideon</description>
            <attack>2</attack>
            <defense>2</defense>
        </card>
        <card summonPoints = '5' type = 'chivalry'>
            <name>Caballero maldito</name>
            <description>la sed de sangre no lo controlarà, 
            su juramento es aun mayor</description>
            <attack>3</attack>
            <defense>2</defense>
        </card>
        <card summonPoints = '5' type = 'lancer'>
            <name>Angel matademonios</name>
            <description>algunos àngeles portegen a los dèbiles e inocentes, yo no</description>
            <attack>5</attack>
            <defense>0</defense>
        </card>
        <card summonPoints = '4' type = 'lancer'>
            <name>Angel de platino</name>
            <description>Ella es la cima del arte, es lo divino tallado en metal</description>
            <attack>0</attack>
            <defense>4</defense>
        </card>
        <card summonPoints = '3' type = 'lancer'>
            <name>Lancero trasgo</name>
            <description>descubrió cuál extremo de la cosa era puntiagudo</description>
            <attack>2</attack>
            <defense>1</defense>
        </card>
        <card summonPoints = '3' type = 'lancer'>
            <name>maestro lancero rhox</name>
            <description>Cuando los rhoxes cargan, los demás saben a donde correr</description>
            <attack>2</attack>
            <defense>1</defense>
        </card>
        <card summonPoints = '5' type = 'infantry'>
            <name>Guerrero abzano</name>
            <description>Alli por donde camino, caminan también los ancestros</description>
            <attack>3</attack>
            <defense>2</defense>
        </card>
        <card summonPoints = '4' type = 'infantry'>
            <name>batallòn infanteria</name>
            <description>¡Siganme! ¡Rompamos esta fila y el resto caerá!</description>
            <attack>2</attack>
            <defense>2</defense>
        </card>
        <card summonPoints = '2' type = 'chivalry'>
            <name>Teferi</name>
            <description>El tiempo no es un problema para mi</description>
            <attack>2</attack>
            <defense>1</defense>
        </card>
        <card summonPoints = '4' type = 'chivalry'>
            <name>caballero tempestad</name>
            <description>E dominado el mar, ya nada podra detenerme</description>
            <attack>4</attack>
            <defense>0</defense>
        </card>
        <card summonPoints = '3' type = 'lancer'>
            <name>General Tazri</name>
            <description>defendere lo que es bueno y justo</description>
            <attack>2</attack>
            <defense>1</defense>
        </card>
        <card summonPoints = '2' type = 'infantry'>
            <name>Maestro ensamblador</name>
            <description>no existe arma que no puedo forjar</description>
            <attack>1</attack>
            <defense>1</defense>
        </card>
        <card summonPoints = '1' type = 'infantry'>
            <name>Ministro impedido</name>
            <description>Cuando aprendes las reglas, no tienes tiempo para romperlas</description>
            <attack>0</attack>
            <defense>1</defense>
        </card>
        <card summonPoints = '5' type = 'lancer'>
            <name>Gigante lotleth</name>
            <description>Un gigante siempre vuelve a levantarse</description>
            <attack>3</attack>
            <defense>2</defense>
        </card>
        <card summonPoints = '2' type = 'infantry'>
            <name>Incursores golgari</name>
        	<description>algun dia volveremos a la superficie</description>
            <attack>0</attack>
            <defense>2</defense>
        </card>
        <card summonPoints = '4' type = 'infantry'>
            <name>Guardabosque</name>
            <description>Solo hay un camino, a menos que vengas conmigo</description>
            <attack>2</attack>
            <defense>2</defense>
        </card>
        <card summonPoints = '3' type = 'lancer'>
            <name>Várolz, el imparable</name>
            <description>nadie puede ante el poder de Várolz</description>
            <attack>3</attack>
            <defense>0</defense>
        </card>
        <card summonPoints = '1' type = 'infantry'>
            <name>elfos de llanowar</name>
            <description>protegeremos la vida</description>
            <attack>0</attack>
            <defense>1</defense>
        </card>
        <card summonPoints = '5' type = 'lancer'>
            <name>comerciante asfoldel</name>
            <description>te vendo lo que sea</description>
            <attack>1</attack>
            <defense>4</defense>
        </card>
        <card summonPoints = '4' type = 'chivalry'>
            <name>merodeador de mogis</name>
            <description>te vendo lo que sea</description>
            <attack>2</attack>
            <defense>2</defense>
        </card>
    </deck>
</PlayerConfig>