<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE PlayerConfig [
    <!ELEMENT PlayerConfig (playerLife, summonPointsPlayer, deck) >
    <!ELEMENT summonPointsPlayer (#PCDATA)>
    <!ELEMENT playerLife (#PCDATA)>
    <!ELEMENT deck (card)+>
    <!ELEMENT card (name, description, attack, defense)>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT description (#PCDATA)>
    <!ELEMENT attack (#PCDATA)>
    <!ELEMENT defense (#PCDATA)>
    <!ATTLIST card summonPoints (0 | 1 | 2 | 3 | 4 | 5) #REQUIRED>
    <!ATTLIST card type (infantry | chivalry | lancer ) #REQUIRED>
]>
 
<PlayerConfig>
    <playerLife>
    
    </playerLife>
    <summonPointsPlayer>
    
    </summonPointsPlayer>
    <deck>
        <card summonPoints = '2' type = 'chivalry'>
            <name>Centauro invertido</name>
            <description>Su mayor temor es que le pongan herraduras en los pies</description>
            <attack>1</attack>
            <defense>1</defense>
        </card>
        <card summonPoints = '3' type = 'chivalry'>
            <name>Abeja Vendepolen</name>
            <description>Una desgracia para los suyos</description>
            <attack>2</attack>
            <defense>1</defense>
        </card>
        <card summonPoints = '4' type = 'chivalry'>
            <name>Vehículo de Corki</name>
            <description>Corki es bueno, pero el es aun mejor</description>
            <attack>2</attack>
            <defense>2</defense>
        </card>
        <card summonPoints = '5' type = 'chivalry'>
            <name>Becario Cargamuros</name>
            <description>Si no transporta los muros le catean la FCT</description>
            <attack>0</attack>
            <defense>5</defense>
        </card>
        <card summonPoints = '5' type = 'chivalry'>
            <name>Kentuky la cabra</name>
            <description>Kentuky significa zorrona en italiano</description>
            <attack>4</attack>
            <defense>1</defense>
        </card>
        <card summonPoints = '2' type = 'lancer'>
            <name>El matemágico</name>
            <description>-"Es un 7 mágico"</description>
            <attack>1</attack>
            <defense>1</defense>
        </card>
        <card summonPoints = '4' type = 'lancer'>
            <name>Becario equilibrado</name>
            <description>Se sacará el ciclo a la primera</description>
            <attack>2</attack>
            <defense>2</defense>
        </card>
        <card summonPoints = '3' type = 'lancer'>
            <name>Goblin emplumado</name>
            <description>Se va a echar a remojo</description>
            <attack>2</attack>
            <defense>1</defense>
        </card>
        <card summonPoints = '5' type = 'lancer'>
            <name>Paco Pincho</name>
            <description>Curtido en las tascas de pintxos de euskadi</description>
            <attack>4</attack>
            <defense>1</defense>
        </card>
        <card summonPoints = '5' type = 'infantry'>
            <name>Zutroy</name>
            <description>-"Doch ni grab ga Mr Burns"</description>
            <attack>3</attack>
            <defense>2</defense>
        </card>
        <card summonPoints = '4' type = 'infantry'>
            <name>Becario mamadisimo</name>
            <description>Muy eficiente en la empresa, aunque pilla mucha baja</description>
            <attack>3</attack>
            <defense>1</defense>
        </card>
        <card summonPoints = '3' type = 'chivalry'>
            <name>Megatron</name>
            <description>Chatarra tu abuela</description>
            <attack>2</attack>
            <defense>1</defense>
        </card>
        <card summonPoints = '4' type = 'chivalry'>
            <name>Valiente ser Robin</name>
            <description>No es tan valiente como dicen las canciones</description>
            <attack>3</attack>
            <defense>1</defense>
        </card>
        <card summonPoints = '3' type = 'lancer'>
            <name>El chico oruga</name>
            <description>El chico oruga se siente guapo</description>
            <attack>2</attack>
            <defense>1</defense>
        </card>
        <card summonPoints = '2' type = 'infantry'>
            <name>Pepe Petardos</name>
            <description>Sufre de leves problemas de sudoracion</description>
            <attack>1</attack>
            <defense>1</defense>
        </card>
        <card summonPoints = '1' type = 'infantry'>
            <name>El chacho migué</name>
            <description>ay los malacatones!!</description>
            <attack>0</attack>
            <defense>1</defense>
        </card>
        <card summonPoints = '4' type = 'lancer'>
            <name>La raspa</name>
            <description>Inventada por Ambrosio con el balon</description>
            <attack>2</attack>
            <defense>2</defense>
        </card>
        <card summonPoints = '3' type = 'infantry'>
            <name>Kresta el payaso</name>
        	<description>¡Hola niños! soy Kresta el payaso</description>
            <attack>0</attack>
            <defense>3</defense>
        </card>
        <card summonPoints = '5' type = 'infantry'>
            <name>Tipo de Incógnito</name>
            <description>¿Quien es Homer? Yo soy tipo de incógnito</description>
            <attack>2</attack>
            <defense>3</defense>
        </card>
        <card summonPoints = '3' type = 'lancer'>
            <name>José Maria Aznar</name>
            <description>España va bien</description>
            <attack>3</attack>
            <defense>0</defense>
        </card>
    </deck>
</PlayerConfig>
